name: sethhoran
favicon: null
layout_spectrum: 0.13048398471437395
typography_spectrum: 0.7515673951711506
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5977302137762308
  lightness: 0.04942126548849046
  saturation: 0.9899518010206521
  rhythmicContrast: 0.7121604348067194
purpose: []
