name: sethhoran
favicon: null
layout_spectrum: 0.25626
typography_spectrum: 0.74708
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050d6a'
    - '#0c28d9'
    - '#7e1c74'
    - '#fc82a3'
    - '#9f4638'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
